# Generated by Django 5.1.4 on 2026-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование работы"
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("oneoff_licensee", "Разовая работа (лицензиат)"),
                            (
                                "longterm_to_licensee",
                                "Периодическая работа ТО (лицензиат)",
                            ),
                            (
                                "smr_licensee",
                                "Строительно-монтажная работа (лицензиат)",
                            ),
                            ("oneoff_lab", "Разовая работа (лаборатория)"),
                            ("longterm_lab", "Периодическая работа (лаборатория)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "company_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("licensee", "Лицензиат"),
                            ("lab", "Лаборатория"),
                            ("subcontractor", "Субподрядчик"),
                        ],
                        db_index=True,
                        max_length=15,
                        null=True,
                        verbose_name="Вид компании",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид работы",
                "verbose_name_plural": "Виды работ",
                "ordering": ["name"],
                "unique_together": {("name", "work_type", "company_kind")},
            },
        ),
    ]
