# Generated by Django 5.1.4 on 2026-01-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contract_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Наименование работы",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("work_oneoff_licensee", "Разовая работа (лицензиат)"),
                            (
                                "work_longterm_to_licensee",
                                "Периодическая работа ТО (лицензиат)",
                            ),
                            ("work_oneoff_lab", "Разовая работа (лаборатория)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Тип работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид работы",
                "verbose_name_plural": "Виды работ",
                "ordering": ["name"],
                "unique_together": {("name", "work_type")},
            },
        ),
        migrations.CreateModel(
            name="ContractWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_works",
                        to="contract_core.contract",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_works",
                        to="contract_works.work",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа договора",
                "verbose_name_plural": "Работы договоров",
                "unique_together": {("contract", "work")},
            },
        ),
    ]
