# Generated by Django 5.1.4 on 2026-01-11 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Макс. 8 цифр', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)], verbose_name='Номер АК')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Абонентский комплект (АК)',
                'verbose_name_plural': 'Абонентские комплекты (АК)',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trash', models.BooleanField(db_index=True, default=False, verbose_name='В корзине')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='В архиве')),
                ('type', models.CharField(choices=[('oneoff_licensee', 'Разовый (лицензиат)'), ('longterm_to_licensee', 'Долгосрочный ТО (лицензиат)'), ('smr_licensee', 'Долгосрочный СМР (лицензиат)'), ('oneoff_lab', 'Разовый (лаборатория)'), ('longterm_lab', 'Долгосрочный (лаборатория)')], db_index=True, max_length=25, verbose_name='Тип договора')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер договора')),
                ('date_concluded', models.DateField(blank=True, null=True, verbose_name='Дата заключения')),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('inn', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='ИНН')),
                ('date_start', models.DateField(verbose_name='Начало действия')),
                ('date_end', models.DateField(verbose_name='Окончание действия')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('file_doc', models.FileField(blank=True, help_text='Не более 20 МБ', upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Документ')),
                ('file_img', models.ImageField(blank=True, help_text='Не более 20 МБ', upload_to='contracts/%Y/%m/', verbose_name='Изображение')),
                ('file_table', models.FileField(blank=True, help_text='Не более 20 МБ', upload_to='contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])], verbose_name='Таблица')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма общая')),
                ('monthly_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма в месяц')),
                ('advance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Аванс')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('active', 'Действует'), ('completed', 'Завершён')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('final_act_date', models.DateField(blank=True, null=True, verbose_name='Дата итогового акта')),
                ('final_act_present', models.BooleanField(default=False, editable=False, verbose_name='Итоговый акт сформирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterimAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Этап Акт', max_length=50, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('file', models.FileField(blank=True, help_text='Не более 20 МБ', upload_to='acts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Файл акта')),
            ],
            options={
                'verbose_name': 'Промежуточный акт',
                'verbose_name_plural': 'Промежуточные акты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Объект защиты',
                'verbose_name_plural': 'Объекты защиты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
    ]
