# Generated by Django 5.1.4 on 2026-02-08 23:27

import apps.contract_core.validators
import datetime
import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Макс. 8 цифр",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                        verbose_name="Номер АК",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("address", models.TextField(verbose_name="Адрес установки")),
            ],
            options={
                "verbose_name": "Абонентский комплект (АК)",
                "verbose_name_plural": "Абонентские комплекты (АК)",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_trash",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="В корзине"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="В архиве"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("oneoff_licensee", "Разовый (лицензиат)"),
                            ("longterm_to_licensee", "Долгосрочный ТО (лицензиат)"),
                            ("oneoff_lab", "Разовый (лаборатория)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Тип договора",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "date_concluded",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата заключения"
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Начало действия")),
                ("date_end", models.DateField(verbose_name="Окончание действия")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        upload_to="contracts/%Y/%m/%d",
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл договора",
                    ),
                ),
                (
                    "total_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма контракта общая",
                    ),
                ),
                (
                    "monthly_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма контракта в месяц",
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Аванс",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("active", "Действует"),
                            ("active_expires", "Истекает"),
                            ("active_expired", "Истёк"),
                            ("completed", "Завершён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договоры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_before_expires",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Если до конца срока ≤ этого числа – статус «Истекает»",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Дней до статуса «Истекает»",
                    ),
                ),
                (
                    "longterm_status_time",
                    models.TimeField(
                        default=datetime.time(2, 0),
                        verbose_name="Время обновления долгосрочных",
                    ),
                ),
                (
                    "oneoff_status_time",
                    models.TimeField(
                        default=datetime.time(3, 0),
                        verbose_name="Время обновления разовых",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки статусов договоров",
                "verbose_name_plural": "Настройки статусов договоров",
            },
        ),
        migrations.CreateModel(
            name="ContractSigningStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стадия подписания договора",
                "verbose_name_plural": "Стадии подписания договоров",
                "ordering": ["changed_at"],
                "permissions": [
                    ("can_edit_signing_stages", "Может редактировать стадии подписания")
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractSystemCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_checked",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последней отметки"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка системы",
                "verbose_name_plural": "Проверки систем",
                "ordering": ["system_type__name"],
                "permissions": [
                    ("can_edit_system_checklist", "Может редактировать чек-лист систем")
                ],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "fias_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Код ФИАС"
                    ),
                ),
                (
                    "district_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Код района"
                    ),
                ),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinalAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "present",
                    models.BooleanField(default=False, verbose_name="Акт сформирован"),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата итогового акта"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        null=True,
                        upload_to="acts_final/%Y/%m/%d",
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл акта",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отметки"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Примечание к акту"
                    ),
                ),
            ],
            options={
                "verbose_name": "Итоговый акт",
                "verbose_name_plural": "Итоговые акты",
                "permissions": [
                    ("can_mark_final_act", "Может отмечать итоговый акт сформированным")
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContract",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "is_trash",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="В корзине"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="В архиве"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("oneoff_licensee", "Разовый (лицензиат)"),
                            ("longterm_to_licensee", "Долгосрочный ТО (лицензиат)"),
                            ("oneoff_lab", "Разовый (лаборатория)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Тип договора",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "date_concluded",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата заключения"
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Начало действия")),
                ("date_end", models.DateField(verbose_name="Окончание действия")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        max_length=100,
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл договора",
                    ),
                ),
                (
                    "total_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма контракта общая",
                    ),
                ),
                (
                    "monthly_sum",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма контракта в месяц",
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Аванс",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("active", "Действует"),
                            ("active_expires", "Истекает"),
                            ("active_expired", "Истёк"),
                            ("completed", "Завершён"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Изменён"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Договор",
                "verbose_name_plural": "historical Договоры",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractSigningStage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Стадия подписания договора",
                "verbose_name_plural": "historical Стадии подписания договоров",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractSystemCheck",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последней отметки"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Примечание"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Проверка системы",
                "verbose_name_plural": "historical Проверки систем",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFinalAct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "present",
                    models.BooleanField(default=False, verbose_name="Акт сформирован"),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата итогового акта"
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        max_length=100,
                        null=True,
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл акта",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Дата отметки"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Примечание к акту"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Итоговый акт",
                "verbose_name_plural": "historical Итоговые акты",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInterimAct",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Этап Акт", max_length=50, verbose_name="Название"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        max_length=100,
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл акта",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Промежуточный акт",
                "verbose_name_plural": "historical Промежуточные акты",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProtectionObject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "contacts",
                    models.TextField(blank=True, null=True, verbose_name="Контакты"),
                ),
                (
                    "total_sum_subcontract",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма субконтракта общая",
                    ),
                ),
                (
                    "monthly_sum_subcontract",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма субконтракта в месяц",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Объект защиты",
                "verbose_name_plural": "historical Объекты защиты",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InterimAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Этап Акт", max_length=50, verbose_name="Название"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                        upload_to="acts/%Y/%m/%d",
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="Файл акта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промежуточный акт",
                "verbose_name_plural": "Промежуточные акты",
                "ordering": ["date"],
                "permissions": [
                    ("can_edit_interim_act", "Может редактировать промежуточные акты")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtectionObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "contacts",
                    models.TextField(blank=True, null=True, verbose_name="Контакты"),
                ),
                (
                    "total_sum_subcontract",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма субконтракта общая",
                    ),
                ),
                (
                    "monthly_sum_subcontract",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма субконтракта в месяц",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект защиты",
                "verbose_name_plural": "Объекты защиты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "fias_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Код ФИАС"
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Код региона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SigningStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название стадии"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Код стадии")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Например, Подписан, Расторжение",
                        verbose_name="Финальная стадия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стадия подписания",
                "verbose_name_plural": "Стадии подписания",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название системы"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг системы")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Тип системы",
                "verbose_name_plural": "Типы систем",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Наименование работы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("work_oneoff_licensee", "Разовая работа (лицензиат)"),
                            (
                                "work_longterm_to_licensee",
                                "Периодическая работа ТО (лицензиат)",
                            ),
                            ("work_oneoff_lab", "Разовая работа (лаборатория)"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Тип работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид работы",
                "verbose_name_plural": "Виды работ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Заказчик"
                    ),
                ),
                (
                    "is_licensee",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Лицензиат МЧС"
                    ),
                ),
                (
                    "is_laboratory",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Лаборатория"
                    ),
                ),
                (
                    "is_subcontractor",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Субподрядчик"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        help_text="10 цифр – юрлицо, 12 – физлицо",
                        max_length=12,
                        unique=True,
                        validators=[apps.contract_core.validators.inn_validator],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "fias_code",
                    models.CharField(
                        blank=True,
                        help_text="Код объекта по ФИАС (необязательно)",
                        max_length=50,
                        null=True,
                        verbose_name="Код ФИАС",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="contract_co_name_0eb145_idx"),
                    models.Index(fields=["inn"], name="contract_co_inn_97dc5c_idx"),
                    models.Index(
                        fields=["is_customer", "name"],
                        name="contract_co_is_cust_14ed96_idx",
                    ),
                    models.Index(
                        fields=["is_licensee", "name"],
                        name="contract_co_is_lice_fd2614_idx",
                    ),
                    models.Index(
                        fields=["is_laboratory", "name"],
                        name="contract_co_is_labo_711871_idx",
                    ),
                    models.Index(
                        fields=["is_subcontractor", "name"],
                        name="contract_co_is_subc_e5ac76_idx",
                    ),
                ],
            },
        ),
    ]
