# Generated by Django 5.1.4 on 2026-01-18 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("contract_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_customer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts_customer",
                to="companies.company",
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind__in": ["licensee", "lab"]},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts_executor",
                to="companies.company",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="ak",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contract_core.district",
                verbose_name="Район установки",
            ),
        ),
        migrations.AddField(
            model_name="interimact",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interim_acts",
                to="contract_core.contract",
            ),
        ),
        migrations.AddField(
            model_name="protectionobject",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="contract_core.contract",
            ),
        ),
        migrations.AddField(
            model_name="protectionobject",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="contract_core.district",
                verbose_name="Район",
            ),
        ),
        migrations.AddField(
            model_name="protectionobject",
            name="subcontractor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "subcontractor"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="protection_objects_sub",
                to="companies.company",
                verbose_name="Субподрядчик",
            ),
        ),
        migrations.AddField(
            model_name="ak",
            name="protection_objects",
            field=models.ManyToManyField(
                blank=True,
                related_name="aks",
                to="contract_core.protectionobject",
                verbose_name="Объекты защиты",
            ),
        ),
        migrations.AddField(
            model_name="protectionobject",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="contract_core.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="contract_core.region",
            ),
        ),
        migrations.AddField(
            model_name="ak",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="contract_core.region",
                verbose_name="Регион установки",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["type", "status"], name="contract_co_type_72bb13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["executor", "status"], name="contract_co_executo_308011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["is_trash"], name="contract_co_is_tras_1ba65e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["is_archived"], name="contract_co_is_arch_ae1d55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("region", "name")},
        ),
        migrations.AddIndex(
            model_name="ak",
            index=models.Index(fields=["number"], name="ak_number_idx"),
        ),
        migrations.AddIndex(
            model_name="ak",
            index=models.Index(
                fields=["region", "district"], name="ak_region_district_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ak",
            unique_together={("number",)},
        ),
    ]
