# Generated by Django 5.1.4 on 2026-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_original_received',
            field=models.BooleanField(default=False, verbose_name='Бумажный оригинал'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_signed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_signed_in_EDO',
            field=models.BooleanField(default=False, verbose_name='ЭДО'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_signed_in_trading_platform',
            field=models.BooleanField(default=False, verbose_name='Торги'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_termination',
            field=models.BooleanField(default=False, verbose_name='Расторжение'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_to_be_signed',
            field=models.BooleanField(default=True, verbose_name='На подписании'),
        ),
        migrations.AddField(
            model_name='contract',
            name='gos_services',
            field=models.BooleanField(default=False, verbose_name='Госуслуги'),
        ),
        migrations.AddField(
            model_name='contract',
            name='oko',
            field=models.BooleanField(default=False, verbose_name='ОКО'),
        ),
        migrations.AddField(
            model_name='contract',
            name='spolokh',
            field=models.BooleanField(default=False, verbose_name='Сполох'),
        ),
    ]
