# Generated by Django 5.1.4 on 2026-02-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalcontract",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractsigningstage",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractsigningstage",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractsystemcheck",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractsystemcheck",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfinalact",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfinalact",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinterimact",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalinterimact",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprotectionobject",
            name="history_change_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprotectionobject",
            name="history_user_id",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signingstage",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг стадии"),
        ),
    ]
