# Generated by Django 5.1.4 on 2026-01-12 08:47

import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_core', '0003_contract_contract_original_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='inn',
            field=models.PositiveIntegerField(help_text='10 цифр ― для юрлиц, 12 ― для физлиц', validators=[apps.contract_core.validators.inn_validator], verbose_name='ИНН'),
        ),
    ]
