# Generated by Django 5.1.4 on 2026-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract_core",
            "0003_alter_historicalcontract_history_change_reason_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcontractsigningstage",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsigningstage",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsigningstage",
            name="history_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsigningstage",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsystemcheck",
            name="checked_by",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsystemcheck",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsystemcheck",
            name="history_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalcontractsystemcheck",
            name="system_type",
        ),
        migrations.RemoveField(
            model_name="historicalfinalact",
            name="checked_by",
        ),
        migrations.RemoveField(
            model_name="historicalfinalact",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalfinalact",
            name="history_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalinterimact",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalinterimact",
            name="history_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalprotectionobject",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="historicalprotectionobject",
            name="district",
        ),
        migrations.RemoveField(
            model_name="historicalprotectionobject",
            name="history_user_id",
        ),
        migrations.RemoveField(
            model_name="historicalprotectionobject",
            name="subcontractor",
        ),
        migrations.DeleteModel(
            name="HistoricalContract",
        ),
        migrations.DeleteModel(
            name="HistoricalContractSigningStage",
        ),
        migrations.DeleteModel(
            name="HistoricalContractSystemCheck",
        ),
        migrations.DeleteModel(
            name="HistoricalFinalAct",
        ),
        migrations.DeleteModel(
            name="HistoricalInterimAct",
        ),
        migrations.DeleteModel(
            name="HistoricalProtectionObject",
        ),
    ]
