# Generated by Django 5.1.4 on 2026-02-16 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract_core",
            "0004_remove_historicalcontractsigningstage_changed_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ak",
            name="address",
            field=models.TextField(
                help_text="Укажите адрес АК (см. базу ОКО)",
                max_length=700,
                verbose_name="Адрес установки",
            ),
        ),
        migrations.AlterField(
            model_name="ak",
            name="name",
            field=models.CharField(
                help_text="Укажите название АК (см. базу ОКО)",
                max_length=255,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="ak",
            name="number",
            field=models.PositiveIntegerField(
                help_text="Макс. 8 цифр. Номер из базы ОКО, например 6001",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99999999),
                ],
                verbose_name="Номер АК",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Укажите краткое название, например: ООО Ромашка или МБДОУ Д/с № 1",
                max_length=255,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_code",
            field=models.CharField(
                blank=True,
                help_text="Код района (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Код района",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="fias_code",
            field=models.CharField(
                blank=True,
                help_text="Код ФИАС (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Код ФИАС",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(
                help_text="Укажите район (муниципальное образование). Например: Тарасовский район или город Азов",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="finalact",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Примечание (необязательно)",
                max_length=200,
                verbose_name="Примечание к акту",
            ),
        ),
        migrations.AlterField(
            model_name="protectionobject",
            name="address",
            field=models.TextField(
                help_text="Укажите почтовый адрес", max_length=700, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="protectionobject",
            name="contacts",
            field=models.TextField(
                blank=True,
                help_text="Укажите контакты (необязательно)",
                null=True,
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="protectionobject",
            name="name",
            field=models.CharField(
                help_text="Назовите объект (здание или помещение), ориентируясь на спецификацию договора, например: Гараж МБУЗ ЦРБ или Главный корпус МБДОУ ДС №1",
                max_length=255,
                verbose_name="Наименование объекта защиты",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="fias_code",
            field=models.CharField(
                blank=True,
                help_text="Код ФИАС (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Код ФИАС",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                help_text="Например: Ростовская область",
                max_length=100,
                unique=True,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_code",
            field=models.CharField(
                blank=True,
                help_text="Код региона (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Код региона",
            ),
        ),
        migrations.AlterField(
            model_name="signingstage",
            name="is_final",
            field=models.BooleanField(default=False, verbose_name="Финальная стадия"),
        ),
        migrations.AlterField(
            model_name="signingstage",
            name="name",
            field=models.CharField(
                help_text="Например: Подписан или Расторжение",
                max_length=50,
                unique=True,
                verbose_name="Название стадии",
            ),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="name",
            field=models.CharField(
                help_text="Например: Сполох",
                max_length=100,
                unique=True,
                verbose_name="Название системы",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Например: Монтаж СПС",
                max_length=255,
                verbose_name="Наименование работы",
            ),
        ),
    ]
