# Generated by Django 5.1.4 on 2026-01-12 09:14

import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_core', '0004_alter_contract_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='inn',
            field=models.CharField(help_text='10 цифр ― для юрлиц, 12 ― для физлиц', max_length=12, validators=[apps.contract_core.validators.inn_validator], verbose_name='ИНН'),
        ),
    ]
