# Generated by Django 5.1.4 on 2026-03-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contract_core",
            "0005_alter_ak_address_alter_ak_name_alter_ak_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectionobject",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_objects",
                to="contract_core.contract",
            ),
        ),
    ]
