# Generated by Django 5.1.4 on 2026-01-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contract_core', '0005_alter_contract_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='executor',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind__in': ['licensee', 'lab']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_executor', to='companies.company', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='protectionobject',
            name='subcontractor',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'subcontractor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protection_objects_sub', to='companies.company', verbose_name='Субподрядчик'),
        ),
    ]
