# Generated by Django 5.1.4 on 2026-03-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0006_alter_protectionobject_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notification_agreed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Компания дала согласие на получение уведомлений",
                verbose_name="Согласие на уведомление",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["notification_agreed"], name="contract_co_notific_a4d873_idx"
            ),
        ),
    ]
