# Generated by Django 5.1.4 on 2026-03-12 16:59

import apps.contract_core.services.uuid_path_generator
import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0007_company_notification_agreed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                upload_to=apps.contract_core.services.uuid_path_generator.contract_file_path,
                validators=[apps.contract_core.validators.file_validator],
                verbose_name="Файл договора",
            ),
        ),
        migrations.AlterField(
            model_name="finalact",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                null=True,
                upload_to=apps.contract_core.services.uuid_path_generator.final_act_file_path,
                validators=[apps.contract_core.validators.file_validator],
                verbose_name="Файл акта",
            ),
        ),
        migrations.AlterField(
            model_name="interimact",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Любой формат, кроме .exe и пр. До 100 МБ",
                upload_to=apps.contract_core.services.uuid_path_generator.act_file_path,
                validators=[apps.contract_core.validators.file_validator],
                verbose_name="Файл акта",
            ),
        ),
    ]
