# Generated by Django 5.1.4 on 2026-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0008_alter_contract_file_alter_finalact_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingstage",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="description",
            field=models.TextField(blank=True, max_length=500, verbose_name="Описание"),
        ),
    ]
