# Generated by Django 5.1.4 on 2026-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0009_signingstage_description_work_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="E-mail компании (необязательно)",
                max_length=254,
                null=True,
                verbose_name="E-mail компании",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Телефон компании (необязательно)",
                max_length=20,
                verbose_name="Телефон компании",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["email"], name="contract_co_email_ed01c4_idx"),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("email",),
                name="unique_company_email",
            ),
        ),
    ]
