# Generated by Django 5.1.4 on 2026-03-22 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0010_company_email_company_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningStageControlSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Количество дней для контроля срока подписания договора",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Количество дней для контроля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка контроля стадий подписания",
                "verbose_name_plural": "Настройки контроля стадий подписания",
            },
        ),
        migrations.AlterField(
            model_name="signingstage",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Чем меньше число, тем выше в списке. Начинайте с 1.",
                verbose_name="Порядок отображения",
            ),
        ),
    ]
