# Generated by Django 5.1.4 on 2026-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0011_signingstagecontrolsettings_alter_signingstage_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание компании (необязательно)",
                max_length=500,
                verbose_name="Описание",
            ),
        ),
    ]
