# Generated by Django 5.1.4 on 2026-01-15 21:20

import apps.contract_core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("licensee", "Лицензиат МЧС"),
                            ("lab", "Лаборатория"),
                            ("subcontractor", "Субподрядчик"),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name="Тип организации",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="10 цифр – юрлицо, 12 – физлицо",
                        max_length=12,
                        validators=[apps.contract_core.validators.inn_validator],
                        verbose_name="ИНН",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("employee", "Сотрудник"),
                        ],
                        default="employee",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "can_delete_contract",
                    models.BooleanField(
                        default=False, verbose_name="Может удалять договоры"
                    ),
                ),
                (
                    "can_edit_systems",
                    models.BooleanField(
                        default=False,
                        verbose_name="Может редактировать чек-лист Системы",
                    ),
                ),
                (
                    "can_edit_sign_stage",
                    models.BooleanField(
                        default=False,
                        verbose_name="Может редактировать чек-лист Стадии подписания",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
