# Generated by Django 5.1.4 on 2026-01-18 03:27

import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Заказчик"
                    ),
                ),
                (
                    "is_licensee",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Лицензиат МЧС"
                    ),
                ),
                (
                    "is_lab",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Лаборатория"
                    ),
                ),
                (
                    "is_subcontractor",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Субподрядчик"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        help_text="10 цифр – юрлицо, 12 – физлицо",
                        max_length=12,
                        unique=True,
                        validators=[apps.contract_core.validators.inn_validator],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "fias_code",
                    models.CharField(
                        blank=True,
                        help_text="Код объекта по ФИАС (необязательно)",
                        max_length=50,
                        verbose_name="Код ФИАС",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
                    models.Index(fields=["inn"], name="companies_c_inn_995f72_idx"),
                    models.Index(
                        fields=["is_customer", "name"],
                        name="companies_c_is_cust_f8530c_idx",
                    ),
                    models.Index(
                        fields=["is_licensee", "name"],
                        name="companies_c_is_lice_436e93_idx",
                    ),
                    models.Index(
                        fields=["is_lab", "name"], name="companies_c_is_lab_e934cf_idx"
                    ),
                    models.Index(
                        fields=["is_subcontractor", "name"],
                        name="companies_c_is_subc_e28d5b_idx",
                    ),
                ],
            },
        ),
    ]
