# Generated by Django 5.1.4 on 2026-02-08 23:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contract_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="телефон"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("bookkeeper", "Бухгалтер"),
                            ("system_manager", "Диспетчер"),
                            ("guest", "Гость"),
                        ],
                        db_index=True,
                        default="guest",
                        max_length=20,
                        verbose_name="категория",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="default_img.png",
                        upload_to="avatars/%Y/%m/%d",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "news_is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Рассылка активна"
                    ),
                ),
                (
                    "can_mark_final_act",
                    models.BooleanField(
                        default=False,
                        help_text="Только для категории MANAGER",
                        verbose_name="может отмечать итоговый акт сформированным",
                    ),
                ),
                (
                    "can_edit_system_checklist",
                    models.BooleanField(
                        default=False,
                        help_text="Только для категории MANAGER",
                        verbose_name="может редактировать чек-лист Системы",
                    ),
                ),
                (
                    "can_edit_signing_stages",
                    models.BooleanField(
                        default=False,
                        help_text="Только для категории MANAGER",
                        verbose_name="может редактировать стадии подписания",
                    ),
                ),
                (
                    "can_edit_interim_act",
                    models.BooleanField(
                        default=False,
                        help_text="Только для категории MANAGER",
                        verbose_name="может редактировать этапные акты",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Пользователь от имени системы (уведомления, чат-боты и т.д.)",
                        verbose_name="Системный пользователь",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="contract_core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник компании",
                "verbose_name_plural": "сотрудники компании",
                "unique_together": {("user", "company")},
            },
        ),
    ]
