# Generated by Django 5.1.4 on 2026-01-12 08:47

import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, help_text='10 цифр ― для юрлиц, 12 ― для физлиц', max_length=12, validators=[apps.contract_core.validators.inn_validator], verbose_name='ИНН'),
        ),
    ]
