# Generated by Django 5.1.4 on 2026-03-09 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract_core", "0007_company_notification_agreed_and_more"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "сотрудник компании",
                "verbose_name_plural": "сотрудники компании",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_edit_interim_act",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_edit_signing_stages",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_edit_system_checklist",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_mark_final_act",
        ),
        migrations.AlterField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="contract_core.company",
                verbose_name="компания",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("guest", "Гость"),
                ],
                db_index=True,
                default="guest",
                max_length=20,
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Пользователь от имени системы",
                verbose_name="системный пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="news_is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="рассылка активна"
            ),
        ),
        migrations.CreateModel(
            name="ManagerPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_mark_final_act",
                    models.BooleanField(
                        default=False,
                        verbose_name="может отмечать итоговый акт сформированным",
                    ),
                ),
                (
                    "can_edit_system_checklist",
                    models.BooleanField(
                        default=False,
                        verbose_name="может редактировать чек-лист Системы",
                    ),
                ),
                (
                    "can_edit_signing_stages",
                    models.BooleanField(
                        default=False,
                        verbose_name="может редактировать стадии подписания",
                    ),
                ),
                (
                    "can_edit_interim_act",
                    models.BooleanField(
                        default=False, verbose_name="может редактировать этапные акты"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "разрешения менеджера",
                "verbose_name_plural": "разрешения менеджеров",
            },
        ),
    ]
