# Generated by Django 5.1.4 on 2026-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_core', '0006_alter_contract_executor_and_more'),
        ('identity', '0002_alter_company_inn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
