# Generated by Django 5.1.4 on 2026-03-12 16:59

import apps.contract_core.services.uuid_path_generator
import apps.contract_core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="название"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.contract_core.services.uuid_path_generator.faq_file_path,
                        validators=[apps.contract_core.validators.file_validator],
                        verbose_name="файл",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="загружен"
                    ),
                ),
            ],
            options={
                "verbose_name": "файл FAQ",
                "verbose_name_plural": "файлы FAQ",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="вопрос")),
                ("answer", models.TextField(verbose_name="ответ")),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="активен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
            ],
            options={
                "verbose_name": "вопрос-ответ",
                "verbose_name_plural": "вопросы и ответы",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
