# Generated by Django 5.1.4 on 2026-01-12 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract_core', '0005_alter_contract_inn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contract_core.contract', verbose_name='Договор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contract', 'timestamp'], name='audit_log_contrac_5135cf_idx'), models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx')],
            },
        ),
    ]
