# Generated by Django 5.1.4 on 2026-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("updated", "Обновлён"),
                            ("trashed", "Удалён в корзину"),
                            ("restored", "Восстановлен из корзины"),
                            ("status_changed", "Изменён статус"),
                            ("date_changed", "Изменены сроки"),
                        ],
                        max_length=20,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Старое значение"
                    ),
                ),
                (
                    "new_value",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Новое значение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время"
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие договора",
                "verbose_name_plural": "События договоров",
                "ordering": ["-created_at"],
            },
        ),
    ]
