# Generated by Django 5.1.4 on 2026-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=50, verbose_name="Поле")),
                (
                    "old_value",
                    models.TextField(blank=True, verbose_name="Старое значение"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, verbose_name="Новое значение"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории",
                "verbose_name_plural": "История изменений",
                "ordering": ["-timestamp"],
            },
        ),
    ]
