# Generated by Django 5.1.4 on 2026-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Должность"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Рассылка активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "companies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Если не выбрано — письмо уйдёт всем, у кого активна рассылка.",
                        related_name="recipients",
                        to="companies.company",
                        verbose_name="Организации",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
