# Generated by Django 5.1.4 on 2026-01-18 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_sound_on",
                    models.BooleanField(default=True, verbose_name="Звук в диалоге"),
                ),
                (
                    "custom_sound",
                    models.FileField(
                        blank=True,
                        upload_to="notifications/dialogues/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg"]
                            )
                        ],
                        verbose_name="Свой звук диалога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диалог",
                "verbose_name_plural": "Диалоги",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Прочитано"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sound_enabled",
                    models.BooleanField(default=True, verbose_name="Звук включён"),
                ),
                (
                    "volume",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Громкость уведомлений",
                    ),
                ),
                (
                    "default_sound",
                    models.FileField(
                        blank=True,
                        upload_to="notifications/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg"]
                            )
                        ],
                        verbose_name="Файл звука по умолчанию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки чата пользователя",
                "verbose_name_plural": "Настройки чатов пользователей",
            },
        ),
    ]
