# Generated by Django 5.1.4 on 2026-03-01 23:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalChatSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_sound",
                    models.FileField(
                        blank=True,
                        help_text="Звук, который будет использоваться для всех уведомлений по умолчанию",
                        upload_to="notifications/global/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg"]
                            )
                        ],
                        verbose_name="Звук уведомления по умолчанию",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Глобальные настройки чата",
                "verbose_name_plural": "Глобальные настройки чата",
            },
        ),
        migrations.AlterModelOptions(
            name="dialogue",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Диалог",
                "verbose_name_plural": "Диалоги",
            },
        ),
        migrations.RemoveField(
            model_name="dialogue",
            name="custom_sound",
        ),
        migrations.RemoveField(
            model_name="dialogue",
            name="is_sound_on",
        ),
        migrations.RemoveField(
            model_name="userchatsettings",
            name="default_sound",
        ),
        migrations.AddField(
            model_name="dialogue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="userchatsettings",
            name="custom_sound",
            field=models.FileField(
                blank=True,
                help_text="Если не загружен - используется глобальный звук",
                upload_to="notifications/users/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg"]
                    )
                ],
                verbose_name="Персональный звук уведомления",
            ),
        ),
        migrations.CreateModel(
            name="UserOnlineStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_online", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус онлайн",
                "verbose_name_plural": "Статусы онлайн",
            },
        ),
    ]
